
server:
  port: 8765


spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: Homework5
          uri: http://localhost:8081/
          predicates:
          - Path=/tasks
          - Path=/tasks/**
          - Path=/status/**
        - id: Microservice2
          uri: http://localhost:8082/
          predicates:
          - Path=/serviceB/**
        - id: Microservice3
          uri: http://localhost:8083/
          predicates:
            - Path=/books/**
            - Path=/books